WebApplicationSheCare/Controllers/MythsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplicationSheCare.Data;
using WebApplicationSheCare.Models;

namespace WebApplicationSheCare.Controllers
{
    public class MythsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public MythsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Myths
        [Authorize]
        public async Task<IActionResult> Index()
        {
              return _context.Myth != null ? 
                          View(await _context.Myth.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.Myth'  is null.");
        }

        // GET: Myths/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Myth == null)
            {
                return NotFound();
            }

            var myth = await _context.Myth
                .FirstOrDefaultAsync(m => m.Id == id);
            if (myth == null)
            {
                return NotFound();
            }

            return View(myth);
        }

        // GET: Myths/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Myths/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Text")] Myth myth)
        {
            if (ModelState.IsValid)
            {
                _context.Add(myth);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(myth);
        }

        // GET: Myths/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Myth == null)
            {
                return NotFound();
            }

            var myth = await _context.Myth.FindAsync(id);
            if (myth == null)
            {
                return NotFound();
            }
            return View(myth);
        }

        // POST: Myths/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Text")] Myth myth)
        {
            if (id != myth.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(myth);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MythExists(myth.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(myth);
        }

        // GET: Myths/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Myth == null)
            {
                return NotFound();
            }

            var myth = await _context.Myth
                .FirstOrDefaultAsync(m => m.Id == id);
            if (myth == null)
            {
                return NotFound();
            }

            return View(myth);
        }

        // POST: Myths/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Myth == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Myth'  is null.");
            }
            var myth = await _context.Myth.FindAsync(id);
            if (myth != null)
            {
                _context.Myth.Remove(myth);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MythExists(int id)
        {
          return (_context.Myth?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

WebApplicationSheCare/Controllers/SuggetionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplicationSheCare.Data;
using WebApplicationSheCare.Models;

namespace WebApplicationSheCare.Controllers
{
    public class SuggetionsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public SuggetionsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Suggetions
        [Authorize]
        public async Task<IActionResult> Index()
        {
              return _context.Suggetions != null ? 
                          View(await _context.Suggetions.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.Suggetions'  is null.");
        }

        // GET: Suggetions/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Suggetions == null)
            {
                return NotFound();
            }

            var suggetion = await _context.Suggetions
                .FirstOrDefaultAsync(m => m.Id == id);
            if (suggetion == null)
            {
                return NotFound();
            }

            return View(suggetion);
        }

        // GET: Suggetions/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Suggetions/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Label,Question,Answer,IsActive")] Suggetion suggetion)
        {
            if (ModelState.IsValid)
            {
                _context.Add(suggetion);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(suggetion);
        }

        // GET: Suggetions/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Suggetions == null)
            {
                return NotFound();
            }

            var suggetion = await _context.Suggetions.FindAsync(id);
            if (suggetion == null)
            {
                return NotFound();
            }
            return View(suggetion);
        }

        // POST: Suggetions/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Label,Question,Answer,IsActive")] Suggetion suggetion)
        {
            if (id != suggetion.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(suggetion);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SuggetionExists(suggetion.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(suggetion);
        }

        // GET: Suggetions/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Suggetions == null)
            {
                return NotFound();
            }

            var suggetion = await _context.Suggetions
                .FirstOrDefaultAsync(m => m.Id == id);
            if (suggetion == null)
            {
                return NotFound();
            }

            return View(suggetion);
        }

        // POST: Suggetions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Suggetions == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Suggetions'  is null.");
            }
            var suggetion = await _context.Suggetions.FindAsync(id);
            if (suggetion != null)
            {
                _context.Suggetions.Remove(suggetion);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SuggetionExists(int id)
        {
          return (_context.Suggetions?.Any(e => e.Id == id)).GetValueOrDefault();
        }
        [Authorize]
        public IActionResult CreateRequest()
        {
            //var suggetions = (ICollection<Suggetion>)_context.Suggetions;
            return View(_context.Suggetions.ToList());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreateRequest(IList<Suggetion> suggetions)
        {
            try
            {
                IList<Suggetion> suggetions1 = suggetions.ToList();
                if (suggetions != null)
                {
                    var blog = from b in suggetions
                               where b.IsActive == true
                               select b;
                    foreach (var suggetion in blog)
                    {
                        var response =
                        _context.Suggetions.FirstOrDefault(t => t.Id == suggetion.Id);
                        suggetions1.Add(response);
                    }
                }
                return View("GenerateResponse", suggetions1);
            }
            catch
            {
                return View(suggetions);
            }
        }
    }
}

WebApplicationSheCare/Views/Shared/_Layout.cshtml
@inject SignInManager<IdentityUser> signInManager;
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplicationSheCare</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApplicationSheCare.styles.css" asp-append-version="true" />
    <link href="~/css/frontend/register_user.css" rel="stylesheet" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.css" />
    @RenderSection("Css", required: false)

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApplicationSheCare</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Suggetions" asp-action="CreateRequest">Get Suggetion</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Myths" asp-action="Index">Manage Myths</a>
                        </li>
                        @* <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                         *@<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Suggetions" asp-action="Index">Manage Suggetion</a>
                        </li>

                    </ul>
                    <ul class="navbar-nav ml-auto">
                        @if (signInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <form method="post" asp-action="logout" asp-controller="account">
                                    <button type="submit" class="nav-link btn btn-link py-0" style="width:auto">
                                        Logout @User.Identity.Name
                                    </button>
                                </form>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Register">Register</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="login">Login</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class=" justify-content-center">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - WebApplicationSheCare - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>